[log]
# log level, acceptable options are: debug, info, warn, error
level = info
# log format, acceptable options are: text, json
format = text


[mysql]
dsn =
# MySQL/MariaDB config file for tuned settings
# Default is /etc/my.cnf.d/conf.d/zz-ssm-tuning.cnf for RedHat based,
# and /etc/mysql/conf.d/zz-ssm-tuning.cnf for Debian based
; tuning_file =


[server]
# SSM server url
url = http://localhost/managed
username =
password =


[tune]
# tuning interval
interval = 60s
# gap limit between config changes, changes will not be applied if the gap since
# last config change is not longer enough
change_gap = 1h